### ISSUE TITLE
Refactor: Replace all instances of os.path with pathlib.Path

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digiarch#102]
It is just easier! Look at this beautiful module: https://docs.python.org/3/library/pathlib.html

**Comment by jnik-aarhus** [comment]
glob/rglob is significantly slower than os.walk, so we'll keep that.

**Comment by clausjuhl** [comment]
Ok. I thought glob would only give a little overhead?

**Comment by clausjuhl** [comment]
Sorry. Thought that you were done :)

**Comment by jnik-aarhus** [comment]
Live on dev: https://github.com/aarhusstadsarkiv/digiarch/commit/da69349be16934075ad3df8aacf97ddc8da34044

**Comment by jnik-aarhus** [comment]
Merged to master
