### ISSUE TITLE
Check out filetype.py for inspiration to file discovery

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digiarch#11]
The [filetype](https://github.com/h2non/filetype.py) package is a simple tool to check files against their [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)). This could serve as inspiration - the package only covers commonly used files, but is open source and the idea could possibly be extended for our needs.

**Comment by clausjuhl** [comment]
Chech out fido. It is used by some institutions in the heritage-world: https://fido.openpreservation.org/

**Comment by clausjuhl** [comment]
Further links for fido:
https://openpreservation.org/technology/products/fido/
http://wiki.opf-labs.org/display/KB/FIDO+usage+guide

**Comment by jnik-aarhus** [comment]
We went with [siegfried](https://github.com/richardlehane/siegfried)
I'd still like to implement our own some day, since the need for external dependencies should be minimised imo.
