### ISSUE TITLE
Generate MD5-checksum while characterizing files

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/digiarch#27]
Save the checksums for later to find and remove duplicates or solve fileextension-mysteries!

Maybe we ought to add the checksums to a global database of files with information about the date of conversion, checksum, original filename, filepath, successful conversion... ?

**Comment by jnik-aarhus** [comment]
This MD5 sum needs to live in `_digiarch/.data/data.json` and should be generated upon **indexing**

**Comment by jnik-aarhus** [comment]
We'll probably use SHA-256 instead of MD5

**Comment by clausjuhl** [comment]
If you really want :) But maybe we should test the difference in processing-time between calculating MD5 vs. SHA-256 on say 100.000 files? When running monthly fixity-checks (in due time) on the entire archive and back-ups, time spend will definately count.
