### ISSUE TITLE
Characterise all received files

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digiarch#30]
Characterise all received files, i.e. check their byte header. Check #11 for inspiration.

**Comment by jnik-aarhus** [comment]
This is also a prerequisite for #27

**Comment by clausjuhl** [comment]
Should this process-step consist of the following:

Initially:
- create process-file in which info about original fileextension, probable fileextension, filename and more is persisted

For each file:
- trim the filename
- if applicable, flag the file with "filename trimmed"
- characterize with fido, filetype or the like and persist probable extension to the process-file, along with original filepath, -name and -extension
- calculate and save MD5-checksum to process-file
- if applicable, rename by appending probable fileextension to original filename, flag with "renamed" in the process-file.

Finally:
- save process-file

**Comment by jnik-aarhus** [comment]
I prefer to have actual processing of files in a separate step, see #31 
So for this, we'd have

Initially:
- create process-file in which info about original fileextension, probable fileextension, filename and more is persisted

For each file:
- ~~trim the filename~~
- ~~if applicable, flag the file with "filename trimmed"~~
- characterize with fido, filetype or the like and persist probable extension to the process-file, along with original filepath, -name and -extension
- calculate and save MD5-checksum to process-file
- ~~if applicable, rename by appending probable fileextension to original filename, flag with "renamed" in the process-file.~~

Finally:
- save process-file

and then in #31 we'd fix with file extensions, trimming etc.

**Comment by jnik-aarhus** [comment]
The process file will probably be a `JSON` file. Easy to read/write in `Python`, integration with `pandas`etc.

**Comment by jnik-aarhus** [comment]
[`python-magic`](https://github.com/ahupp/python-magic) looks very promising.

**Comment by jnik-aarhus** [comment]
This is worked on in branch [iss30-id-files](https://github.com/aarhusstadsarkiv/digital-archive/tree/iss30-id-files)

**Comment by jnik-aarhus** [comment]
New branch: https://github.com/aarhusstadsarkiv/digiarch/tree/iss30-identify-files

**Comment by jnik-aarhus** [comment]
This is closed with #134
