### ISSUE TITLE
Investigate using test corpora for validation

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/digiarch#47]
Could we use test-corpora to validate our choices in chraracterization-tools? The following two look promising:

- https://openpreservation.org/technology/corpora/govdocs-selected/
- https://openpreservation.org/technology/corpora/opf-format-corpus/

**Comment by jnik-aarhus** [comment]
Would be interesting to also use the skeleton suite files from here: https://github.com/exponential-decay/pronom-archive-and-skeleton-test-suite/releases/tag/skeleton-test-suite-2019-05-09-sig-file-v95
We can obtain them programmatically using 
```bash
curl -s https://api.github.com/repos/exponential-decay/pronom-archive-and-skeleton-test-suite/releases/latest
```
