### ISSUE TITLE
Produce & reference file blacklist

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/digiarch#48]
If we haven't yet made one, I suggest that we produce and reference a blacklist of fileformats that we do not have to convert, eg. thumbs.db, .exe, .lnk...

**Comment by kpind-aarhus** [comment]
.id files should probably be blacklisted as they only contain passwords and user information: https://fileinfo.com/extension/id

What do we do with files we chose not to convert?
