### ISSUE TITLE
UnicodeError in report-generation on Windows 10

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/digiarch#80]
# Bug Description

Report-generation throws a UnicodeError when trying to render emojis:
![digiarch_utf8-bug](https://user-images.githubusercontent.com/2181410/67681802-5350fe80-f98e-11e9-846a-e88c1971de08.PNG)

# Expected Behaviour

Beautiful emojis rendered perfectly in the shell!

# Steps to Reproduce

1. Open gitbash on Windows 10
2. cd to virtual env with idigital-archive installed via pip
2. run "digiarch . report"

# System Information

* **Operating System:** 
Windows 10 Pro, version 1809, build 17763.805

- **How did you run the project?**
  - [ ] Using `poetry` 
  - [x] Using `python`

**Comment by jnik-aarhus** [comment]
Fixed in dev branch https://github.com/aarhusstadsarkiv/digiarch/tree/development. Will close when dev is merged to master
