### ISSUE TITLE
is_empty_sub flag in data.json is confusing

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/digiarch#81]
Each entry in data.json has a 'is_empty_sub' flag, but when an entry represents a file, the flag is always false, and when representing an empty folder, it is always true. Should we remove all other keys (which are always empty) when representing empty folder?

Does it make sense?

**Comment by jnik-aarhus** [comment]
We need to refactor the `FileInfo` dataclass to remove the flag:

```python 
@dataclasses.dataclass
class FileInfo:
    """Dataclass for keeping track of file information"""

    name: str = ""
    ext: str = ""
    **is_empty_sub: bool = False**
    path: str = ""
    mimetype: str = ""
    guessed_ext: str = ""
```  
We should simply report on empty subfolders in the indexing step, as it is not really a report but rather a warning.
